### ISSUE TITLE
1.1.1版本会造成闪退 、Recursive entry to executePendingTransactions

### ISSUE THREAD

**Issue by tcxdawn** [bingoogolapple/BGARefreshLayout-Android#28]
E/AndroidRuntime: FATAL EXCEPTION: main
                                     java.lang.IllegalStateException: Recursive entry to executePendingTransactions
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1585)
                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                         at android.os.Handler.handleCallback(Handler.java:725)
                                         at android.os.Handler.dispatchMessage(Handler.java:92)
                                         at android.os.Looper.loop(Looper.java:137)
                                         at android.app.ActivityThread.main(ActivityThread.java:5069)
                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                         at java.lang.reflect.Method.invoke(Method.java:511)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                         at dalvik.system.NativeStart.main(Native Method)

  compile 'cn.bingoogolapple:bga-refreshlayout:1.1.1@aar'
我的主程序是ViewPager +TabLayout；ViewPager 包含fragment 
其中有一个fragment 使用了BGARefreshLayout。之前用的是1.0.7版本没有问题。然后改成1.1.1就闪退了

**Comment by tcxdawn** [comment]
手动测试了下 1.0.8也不会。然后1.0.9,1.1.0也是会闪退

**Comment by bingoogolapple** [comment]
@tcxdawn 1.1.2会不会有这个问题？

**Comment by tcxdawn** [comment]
@bingoogolapple 解决掉了。好像是新版本的BGAMoocStyleRefreshViewHolder这个要设置图片，然后没有。然后我换到最新的1.1.3也可以用
